# Site settings
course_name: "CS290: PhD Grad Cohort Research Seminar"
course_description: "This course is designed for entering computer science Ph.D. students. The goals of the course are three-fold: (1) to introduce students to research around the CS area, (2) skills building, and (3) cohort building. We will lead sessions on skill building (paper reading, presentation, meaning of research) and soft skill building (advising relationships, academic culture, mental health, supporting your peers), as well as research and professional oriented discussions with a broad mixture of CS faculty members. We will also “visit” and discuss one or two CS colloquia. This is a full-year, 4-unit course, meeting once a week in each of the fall and the spring. Students must complete both terms of this course (parts A and B) within the same academic year to receive credit."
course_semester: "Fall 2021 - Spring 2022"

baseurl: "/harvard-cs290/" # the subpath of your site, e.g. /blog/
url: "http://yanivyacoby.github.io/" # the base hostname & protocol for your site

schoolname: "Harvard SEAS"
schoolurl: "https://www.seas.harvard.edu/"
#twitter_username: username 

#address: |
#    School of Witchcraft and Wizardry
#    Hogwarts
#    Scotland

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
